#!/bin/bash

cmd="$1"

if [[ -f "$cmd" && -x "$cmd" ]]; then
    sudo cp "$cmd" /usr/local/bin/
    
    sudo chmod 755 /usr/local/bin/"$(basename "$cmd")"
    
    echo "Command '$cmd' registered successfully."
else
    echo "File '$cmd' does not exist or is not executable."
    exit 1
fi
